name: QA L0 PYTHORCH Unittest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  qa-l0-pytorch-unittest:
    runs-on: [ self-hosted, Linux, X64, nvida, gpu-8 ]
    defaults:
      run:
        shell: bash
    container:
      image: harbor.baai.ac.cn/flagscale/cuda12.8.1-cudnn9.10.2-torch2.9.1-py3.10-transformerengine_fl:20260204
      ports:
        - 80:80
      options: >-
        --gpus all 
        --shm-size=500g 
        --privileged 
        --ipc=host 
        --ulimit memlock=-1 
        --ulimit stack=67108864 
        --ulimit nofile=65535:65535 
        --user root
        --pull always

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: recursive
          set-safe-directory: true

      - name: Pre-Check Environment
        timeout-minutes: 5
        run: |
          set -euo pipefail
          echo "===== System Info ====="
          uname -a
          python3 --version || (echo "❌ python3 not found"; exit 1)
          pip3 --version || (echo "❌ pip3 not found"; exit 1)

          echo "===== GPU Info ====="
          if command -v nvidia-smi &>/dev/null; then
            nvidia-smi --query-gpu=index,name,memory.total,utilization.gpu --format=csv
          else
            echo "⚠️ GPU check skipped. nvidia-smi is not available in the current environment."
            exit 1
          fi

          nvcc --version || echo "⚠️ nvcc not found (non-fatal for python-only install)"

          echo "===== Disk Space ====="
          df -h

          echo "===== Available memory ====="
          free -h

      - name: Install dependencies and build transformer_engine
        timeout-minutes: 30
        run: |
          echo "\n=============== Install transformer_engine ==============="
          pip install --no-build-isolation -vvv . --no-deps
          cp -rf transformer_engine/plugins/ /usr/local/lib/python3.10/dist-packages/transformer_engine/plugins/

      - name: Verify installation
        shell: bash
        run: |
          python3 tests/pytorch/test_sanity_import.py

      - name: GPU Usage Check / Verification
        run: |
          source .github/workflows/scripts/gpu_check.sh
          wait_for_gpu
   
      - name: L0 Pytorch Debug Unittest
        id: L0_pytorch_debug_unittest
        continue-on-error: true
        timeout-minutes: 10
        env:
          XML_LOG_DIR: "/logs/pytorch/debug"
          TE_PATH: .
        run: |
          ignore_files=("tests/pytorch/debug/test_api_features.py" "tests/pytorch/test_numerics.py")

          for file in "${ignore_files[@]}"; do
              escaped_file=$(echo "$file" | sed 's/\//\\\//g')
              sed -i "s/^.*\($escaped_file\).*$/#&/" ./qa/L0_pytorch_debug_unittest/test.sh
          done

          cat ./qa/L0_pytorch_debug_unittest/test.sh

          bash ./qa/L0_pytorch_debug_unittest/test.sh

      - name: L0 Pytorch Unittest
        id: L0_pytorch_unittest
        timeout-minutes: 20
        env:
          XML_LOG_DIR: "/logs/pytorch"
          TE_PATH: .
        run: |
          ignore_files=("tests/pytorch/test_numerics.py" "tests/pytorch/test_permutation.py" 
              "tests/pytorch/attention/test_attention.py" "tests/pytorch/test_checkpoint.py"
          )

          for file in "${ignore_files[@]}"; do
              escaped_file=$(echo "$file" | sed 's/\//\\\//g')              
              sed -i "s/^.*\($escaped_file\).*$/#&/" ./qa/L0_pytorch_unittest/test.sh
          done

          cat ./qa/L0_pytorch_unittest/test.sh

          bash ./qa/L0_pytorch_unittest/test.sh

      - name: Upload Installation Logs
        if: always() && (steps.L0_pytorch_unittest.outcome == 'failure' || steps.L0_pytorch_debug_unittest.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: L0_pytorch-logs-${{ github.run_id }}
          path: /logs/pytorch
          retention-days: 7
          if-no-files-found: warn
